import crypto from "crypto";
import { MercadoPagoConfig, PreApproval } from "mercadopago";
import { isPaymentTestMode, resolvePayerEmail, resolvePaymentAmount } from "@/lib/payments";

if (!process.env.MERCADOPAGO_ACCESS_TOKEN) {
  console.warn("MERCADOPAGO_ACCESS_TOKEN is not defined in .env");
}

export const mpClient = new MercadoPagoConfig({
  accessToken: process.env.MERCADOPAGO_ACCESS_TOKEN || "TEST-PLACEHOLDER",
});

export const SUBSCRIPTION_PLANS: Record<string, { name: string, amount: number, description: string, planId?: string }> = {
  USER: {
    name: "MeetOff Usuários",
    amount: resolvePaymentAmount(170.3),
    description: "Assinatura Mensal MeetOff para Usuários",
    planId: "69ce9463cda24799b9c5a3b613001df0" // ID do plano criado no painel
  },
  PARTNER: {
    name: "MeetOff Empresas/Parceiros",
    amount: resolvePaymentAmount(232.7),
    description: "Assinatura Mensal MeetOff para Empresas e Parceiros",
  },
};

export class MercadoPagoService {
  /**
   * Create a pre-approval (subscription)
   * IMPORTANT: The seller email cannot be the same as the payer email.
   * If testing with your own account, use a different email in the checkout.
   */
  static async createSubscription(userId: string, userEmail: string, planType: 'USER' | 'PARTNER') {
    const planData = SUBSCRIPTION_PLANS[planType];
    const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || "https://meet-off.vercel.app").replace(/\/$/, "");

    try {
      const body: any = {
        reason: planData.name,
        payer_email: userEmail.trim().toLowerCase(),
        back_url: `${baseUrl}/account`,
        external_reference: userId,
        auto_recurring: {
          frequency: 1,
          frequency_type: "months",
          transaction_amount: planData.amount,
          currency_id: "BRL",
        }
      };

      console.log("FINAL SUBMISSION BODY:", JSON.stringify(body, null, 2));

      // Usando fetch direto para maior controle e estabilidade com a API do Mercado Pago
      const response = await fetch("https://api.mercadopago.com/preapproval", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`
        },
        body: JSON.stringify(body)
      });

      const data = await response.json();

      if (!response.ok) {
        console.error("MP ERROR RESPONSE:", JSON.stringify(data, null, 2));

        let errorMessage = data.message || "Erro na API do Mercado Pago";
        
        // Mercado Pago often returns a generic 500 error when you try to test
        // a checkout using the same email as the Mercado Pago seller account.
        if (response.status === 500 && data.message === "Internal server error") {
          errorMessage = "Erro interno do MP (500). Isso geralmente ocorre se você usar o email da sua conta Mercado Pago no checkout. Tente com um email diferente (ex: teste@gmail.com).";
        }

        throw {
          message: errorMessage,
          status: response.status,
          details: data
        };
      }

      const initPoint = (process.env.MERCADOPAGO_ACCESS_TOKEN?.startsWith("TEST-") && data.sandbox_init_point)
        ? data.sandbox_init_point
        : data.init_point;

      return {
        init_point: initPoint,
        id: data.id
      };
    } catch (error: any) {
      console.error("Error creating subscription:", error);
      throw error;
    }
  }

  /**
   * Create and authorize a subscription from a card token generated by Mercado Pago Bricks.
   * Card data never reaches this server; only the temporary token is submitted.
   */
  static async createTransparentSubscription(
    userId: string,
    userEmail: string,
    planType: 'USER' | 'PARTNER',
    cardTokenId: string,
  ) {
    const planData = SUBSCRIPTION_PLANS[planType];
    const baseUrl = (process.env.NEXT_PUBLIC_APP_URL || "https://meet-off.vercel.app").replace(/\/$/, "");

    try {
      const body: any = {
        reason: planData.name,
        payer_email: userEmail.trim().toLowerCase(),
        card_token_id: cardTokenId,
        back_url: `${baseUrl}/account`,
        external_reference: userId,
        status: "authorized",
        auto_recurring: {
          frequency: 1,
          frequency_type: "months",
          transaction_amount: planData.amount,
          currency_id: "BRL",
        }
      };

      const response = await fetch("https://api.mercadopago.com/preapproval", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`
        },
        body: JSON.stringify(body)
      });

      const data = await response.json();

      if (!response.ok) {
        console.error("MP TRANSPARENT SUBSCRIPTION ERROR:", JSON.stringify(data, null, 2));

        let errorMessage = data.message || "Erro na API do Mercado Pago";
        if (data.cause?.[0]?.description) {
          errorMessage = data.cause[0].description;
        }

        throw {
          message: errorMessage,
          status: response.status,
          details: data
        };
      }

      return {
        id: data.id,
        status: data.status,
        next_payment_date: data.next_payment_date,
      };
    } catch (error: any) {
      console.error("Error creating transparent subscription:", error);
      throw error;
    }
  }

  static async createProductPayment({
    orderId,
    productName,
    amount,
    userEmail,
    cardTokenId,
    paymentMethodId,
    issuerId,
    installments,
    identificationType,
    identificationNumber,
  }: {
    orderId: string;
    productName: string;
    amount: number;
    userEmail: string;
    cardTokenId: string;
    paymentMethodId: string;
    issuerId?: string;
    installments?: number;
    identificationType?: string;
    identificationNumber?: string;
  }) {
    const paymentAmount = resolvePaymentAmount(amount);
    const payerEmail = resolvePayerEmail(userEmail);
    const body: any = {
      transaction_amount: paymentAmount,
      token: cardTokenId,
      description: productName,
      installments: installments || 1,
      payment_method_id: paymentMethodId,
      external_reference: orderId,
      payer: {
        email: payerEmail.trim().toLowerCase(),
      },
    };

    if (issuerId) {
      body.issuer_id = issuerId;
    }

    if (identificationType && identificationNumber) {
      body.payer.identification = {
        type: identificationType,
        number: identificationNumber,
      };
    }

    const response = await fetch("https://api.mercadopago.com/v1/payments", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`,
        "X-Idempotency-Key": crypto.randomUUID(),
      },
      body: JSON.stringify(body),
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("MP PRODUCT PAYMENT ERROR:", JSON.stringify(data, null, 2));

      let errorMessage = data.message || "Erro ao processar pagamento";
      if (data.cause?.[0]?.description) {
        errorMessage = data.cause[0].description;
      }
      if (response.status === 500 && data.message === "internal_error") {
        errorMessage = isPaymentTestMode()
          ? "Erro interno do Mercado Pago em modo teste. Confira se MERCADOPAGO_ACCESS_TOKEN e NEXT_PUBLIC_MERCADOPAGO_PUBLIC_KEY sao credenciais TEST da mesma aplicacao."
          : "Erro interno do Mercado Pago. Tente novamente em alguns instantes.";
      }

      throw {
        message: errorMessage,
        status: response.status,
        details: data,
      };
    }

    return {
      id: data.id,
      status: data.status,
      status_detail: data.status_detail,
    };
  }

  static async getPayment(paymentId: string) {
    const response = await fetch(`https://api.mercadopago.com/v1/payments/${paymentId}`, {
      headers: {
        "Authorization": `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`,
      },
    });

    const data = await response.json();

    if (!response.ok) {
      throw {
        message: data.message || "Erro ao consultar pagamento",
        status: response.status,
        details: data,
      };
    }

    return data;
  }

  /**
   * Get subscription details
   */
  static async getSubscription(preApprovalId: string) {
    const preApproval = new PreApproval(mpClient);
    try {
      return await preApproval.get({ id: preApprovalId });
    } catch (error) {
      console.error("Error getting MP subscription:", error);
      throw error;
    }
  }

  /**
   * Cancel subscription
   */
  static async cancelSubscription(preApprovalId: string) {
    const preApproval = new PreApproval(mpClient);
    try {
      return await preApproval.update({
        id: preApprovalId,
        body: { status: "cancelled" }
      });
    } catch (error) {
      console.error("Error cancelling MP subscription:", error);
      throw error;
    }
  }
}
